### PR TITLE
More Style

### PR DESCRIPTION
**Pull request by sokrahta**
Added some more style checks.
Updated code to remove build warns/errs caused by the additions.
Added documentation.

Scala Style Checkers added
-----------------------------------
ProcedureDeclarationChecker - methods that return ```Unit``` must have ```=``` between signature and block.
RegexChecker - declaration modifiers in specific order.
ClassTypeParameterChecker - generic types must be single underscore or capital letter.
DeprecatedJavaChecker - use correct deprecated annotation.
EmptyClassChecker - exclude braces for empty class/trait.
FieldNamesChecker - fields are camel cased.
ForBraceChecker - always use braces in for-comprehension, never parens with semicolons.
ImportGroupingChecker - all imports in one spot, usually near the top.
LowercasePatternMatchChecker - prohibit confusing lowercase pattern match cases.
MultipleStringLiteralsChecker - literal string that occurs more than once should be a constant.
NonASCIICharacterChecker - require only ascii characters, protects ```=>``` from unicode arrows and such.
RedundantIfChecker - replace ```if (x) false else true``` with ```!x``` and similar.
ScalaDocChecker - **disabled** due to [issue 123](https://github.com/scalastyle/scalastyle/issues/123)
SpaceAfterCommentStartChecker - consistent comment spacing.
VarFieldChecker - prohibit mutable fields.
VarLocalChecker - allow mutable locals.

[Review on Reviewable](https://reviewable.io/reviews/socrata/socrata-sbt-plugins/6)

### CODE REVIEW

**Comment by velvia** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/socrata/socrata-sbt-plugins/6)







---

<sup>**[src/main/resources/scalastyle-config.xml, line 28 \[r1\]](https://reviewable.io:443/reviews/socrata/socrata-sbt-plugins/6#-JgHNSgIAK2cPELSaR3-)** ([raw file](https://github.com/socrata/socrata-sbt-plugins/blob/6cde66e4c55aef6c00909ea3ff61637e179a586f/src/main/resources/scalastyle-config.xml#L28)):</sup>
The first character of a field name may be uppercase -- we do this for Constants.

---

<sup>**[src/main/resources/scalastyle-config.xml, line 38 \[r1\]](https://reviewable.io:443/reviews/socrata/socrata-sbt-plugins/6#-JgHNeFRK40Rtl4fuXC-)** ([raw file](https://github.com/socrata/socrata-sbt-plugins/blob/6cde66e4c55aef6c00909ea3ff61637e179a586f/src/main/resources/scalastyle-config.xml#L38)):</sup>
It should be possible for class type parameters to be more than one char for clarity

---

<sup>**[src/main/resources/scalastyle-config.xml, line 130 \[r1\]](https://reviewable.io:443/reviews/socrata/socrata-sbt-plugins/6#-JgHNmcaDb_0SN6yECdh)** ([raw file](https://github.com/socrata/socrata-sbt-plugins/blob/6cde66e4c55aef6c00909ea3ff61637e179a586f/src/main/resources/scalastyle-config.xml#L130)):</sup>
This is a good idea in theory, but may not be possible to pass for certain parts of our stack.  I guess we can exclude certain lines from stylecheck.

---

**Comment by velvia** [comment]
In general I would test all these new rules against existing repos like soda-fountain to see the results.

**Comment by sokrahta** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/socrata/socrata-sbt-plugins/6)



---

Tested against soda-fountain and got these style hits, newly proposed rules (bolded) make up 221 / 785 style issues.

168 org.scalastyle.scalariform.PublicMethodsHaveTypeChecker
139 org.scalastyle.file.FileLineLengthChecker
**89 org.scalastyle.scalariform.MultipleStringLiteralsChecker**
62 org.scalastyle.scalariform.MagicNumberChecker
**52 org.scalastyle.scalariform.ProcedureDeclarationChecker**
51 org.scalastyle.scalariform.IfBraceChecker
30 org.scalastyle.scalariform.NullChecker
28 org.scalastyle.scalariform.ReturnChecker
**24 org.scalastyle.scalariform.ImportGroupingChecker**
**19 org.scalastyle.scalariform.LowercasePatternMatchChecker**
19 org.scalastyle.file.NewLineAtEofChecker
**16 org.scalastyle.scalariform.ForBraceChecker**
**15 org.scalastyle.scalariform.SpaceAfterCommentStartChecker**
14 org.scalastyle.scalariform.CyclomaticComplexityChecker
13 org.scalastyle.file.RegexChecker *(these were all semicolons, not the new modifier order check)*
12 org.scalastyle.scalariform.ClassNamesChecker
11 org.scalastyle.scalariform.ParameterNumberChecker
11 org.scalastyle.scalariform.MethodLengthChecker
2 org.scalastyle.scalariform.VarFieldChecker *(to be disabled)*
2 org.scalastyle.scalariform.ObjectNamesChecker
2 org.scalastyle.scalariform.MethodNamesChecker
1 org.scalastyle.scalariform.StructuralTypeChecker
1 org.scalastyle.scalariform.SpacesBeforePlusChecker
1 org.scalastyle.scalariform.SpacesAfterPlusChecker
1 org.scalastyle.scalariform.NumberOfTypesChecker
1 org.scalastyle.scalariform.ClassTypeParameterChecker *(to be disabled)*
1 org.scalastyle.file.WhitespaceEndOfLineChecker

---

<sup>**[src/main/resources/scalastyle-config.xml, line 28 \[r1\]](https://reviewable.io:443/reviews/socrata/socrata-sbt-plugins/6#-JgHNSgIAK2cPELSaR3-)** ([raw file](https://github.com/socrata/socrata-sbt-plugins/blob/6cde66e4c55aef6c00909ea3ff61637e179a586f/src/main/resources/scalastyle-config.xml#L28)):</sup>
Didn't occur in soda-fountain; scalastyle apparantly differentiates between fields and constants. The code below is valid style with an uppercase constant id. Like to leave this one in for now.

```
object QueryCoordinatorClient {
  ...
  val HeaderRollup = "X-SODA2-Rollup"
}
```

but in other places it expects lowercase field id.
```

abstract class HttpDataCoordinatorClient(httpClient: HttpClient) extends DataCoordinatorClient {
...
  val xhCopyNumber = "X-SODA2-Truth-Copy-Number"
...
```

---

<sup>**[src/main/resources/scalastyle-config.xml, line 38 \[r1\]](https://reviewable.io:443/reviews/socrata/socrata-sbt-plugins/6#-JgHNeFRK40Rtl4fuXC-)** ([raw file](https://github.com/socrata/socrata-sbt-plugins/blob/6cde66e4c55aef6c00909ea3ff61637e179a586f/src/main/resources/scalastyle-config.xml#L38)):</sup>
Found this only once in soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/JsonColumnRep.scala
```class CodecBasedJsonColumnRep[TrueCV : JsonCodec](val representedType: SoQLType, unwrapper: SoQLValue => TrueCV, wrapper: TrueCV => SoQLValue) extends JsonColumnRep {```

But sounds reasonable, I'll disable this check for all.

---

<sup>**[src/main/resources/scalastyle-config.xml, line 130 \[r1\]](https://reviewable.io:443/reviews/socrata/socrata-sbt-plugins/6#-JgHNmcaDb_0SN6yECdh)** ([raw file](https://github.com/socrata/socrata-sbt-plugins/blob/6cde66e4c55aef6c00909ea3ff61637e179a586f/src/main/resources/scalastyle-config.xml#L130)):</sup>
Found this twice, but the first instance actually looks like a local not a field. So if it's going to false positive better just disable it for now and mark an [issue in scalastyle](https://github.com/scalastyle/scalastyle/issues/132).

soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/HttpDataCoordinatorClient.scala
```var pendingIterator: Iterator[JValue] = null```
soda-fountain-war/src/main/scala/com/socrata/soda/server/SodaFountainServlet.scala
```var fountain: SodaFountain = null```

---

**Comment by sokrahta** [comment]
Stupid cloudbees
[info] [0m[[31merror[0m] [0m(*:[31mivySbt[0m) Could not create file /tmp/sbt_44c212b5/Coverage/target/streams/$global/ivySbt/$global/streams/outjava.io.IOException: No such file or directory[0m

**Pull request merged**
